### PR TITLE
Python2 and 3 compatible metaclass support

### PR DESCRIPTION
**Pull request by JustinVenus**
Minor changes to support python2 and python3 metaclasses.

### CODE REVIEW

**Comment by JustinVenus** [comment]
I had to make a small fix and I force pushed the branch to keep the history clean.  Here's the result of running tests.

```sh
jvenus-signal-mbp13:scales jvenus$ ./runtests.sh
...No handlers could be found for logger "scales.loadbalancer.ApertureBalancerSink.[mock]"
................................................
----------------------------------------------------------------------
Ran 51 tests in 1.858s

OK
```

**Comment by steveniemitz** [comment]
Sorry I just force pushed master because I noticed it was slightly out of date from my local copy, can you rebase?

**Comment by JustinVenus** [comment]
Sure thing

**Comment by steveniemitz** [comment]
⚡️ looks good, thanks for the contribution!

**Pull request merged**
